[package]
name = "pyrust-example"
version = "0.1.0"
authors = ["Matt Keibler <wanderingelf14@gmail.com>"]

[dependencies]
pyo3 = { version="0.2.3", features=["extension-module"] }

[lib]
name = "pyrust_example"
crate-type = ["cdylib"]